# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  upload-compiled-binary:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install rustup
        # You may pin to the exact commit or the version.
        # uses: EgorDm/gha-yarn-node-cache@5e3a518810b21a8e0e1d236a3db83a18cfc1be9e
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y

      - name: setup rustup
        run: |
          /usr/bin/rustup override set 1.60
          /usr/bin/rustup target add x86_64-pc-windows-gnu

      - name: install deps
        run: sudo apt install -y libpango-1.0-0 libatk1.0-0 mingw-w64 librust-atk-dev librust-gdk-dev

      - name: compile linux
        run: /usr/bin/cargo build --release

      - name: compile windows
        run: /usr/bin/cargo build --target=x86_64-pc-windows-gnu --release

      - name: version
        run: echo "::set-output name=version::$(./target/release/freedeck-companion -v)"
        id: version

      - name: zip up linux
        run: zip -j freedeck-companion-linux ./target/release/freedeck-companion ./target/release/icon.png

      - name: zip up windows
        run: freedeck-companion-windows ./target/x86_64-pc-windows-gnu/release/freedeck-companion.exe

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: true
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./freedeck-companion-linux.zip
          asset_name: freedeck-companion-linux.zip
          asset_content_type: application/zip
      - name: upload windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./freedeck-companion-windows.zip
          asset_name: freedeck-companion-windows.zip
          asset_content_type: application/zip
